"""added user_id to content

Revision ID: d4a987f85b5c
Revises: 9f26a951b376
Create Date: 2026-04-15 12:17:41.514571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a987f85b5c'
down_revision: Union[str, Sequence[str], None] = '9f26a951b376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'user_id')
    # ### end Alembic commands ###
