"""added content hash

Revision ID: ff47afa8ecf3
Revises: 5d92d77462e6
Create Date: 2026-04-27 12:19:02.839377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff47afa8ecf3'
down_revision: Union[str, Sequence[str], None] = '5d92d77462e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_contents_content_hash'), 'contents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_content_hash'), table_name='contents')
    op.drop_column('contents', 'content_hash')
    # ### end Alembic commands ###
